# Generated by Django 4.2 on 2024-08-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_ID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
