# Generated by Django 5.1 on 2024-08-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_hits_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_view_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
