# Generated by Django 5.1 on 2024-08-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_last_view_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_view_time',
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
